---
title: JPE Replication Report
date: today
number-sections: true
format:
  html: default
---

# Paper Identification

|  |   |
| ---  |  -------|
| ID  |  {{< var paper_id >}} |
| Author  |  Luca Marcianò |
| Title  |  Intergenerational Mobility and maternal age at birth |
| Iteration |  {{< var round >}} |


Some useful information up front:

- [JPE Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy)
- [Step by step guidance from Data Editor for Authors](https://jpedataeditor.github.io/) 
- [Template README](https://social-science-data-editors.github.io/template_README/)



# Summary


In assessing compliance with our [Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy), our reproducibility team has identified the following issues, which we ask you to address:

1. Data Editor's first point.
2. Data Editor's second point.

# General

- [X] Data Availability and Provenance Statements
  - [X] Statement about Rights - Part 1: Right to use the data (e.g. *did the authors lawfully obtain the data*)
  - [X] Statement about Rights - Part 2: Right to publish the data (e.g. *are human subjects involved and did permission been granted to publish their data?*)
  - [X] License for Data (optional, but recommended)
  - [X] Details on each Data Source
- [X] Dataset list
- [X] Computational requirements
  - [X] Software Requirements
  - [X] Controlled Randomness (as necessary)
  - [X] Memory, Runtime, and Storage Requirements
- [X] Description of programs/code
  - [X] License for Code (Optional, but recommended) 
- [X] List of tables and programs
- [X] References (Optional, but recommended) 


# High-level Description of Research Project

*This research project...*

- [X] uses observational data.
- [ ] uses *confidential* observational data.
- [ ] uses data generated via experiment or trial by the authors (in field or lab).
  - [ ] For lab experiments: The code to implement the experimental protocol (z-Tree, o-Tree etc) is included in the package.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF document outlining the design of the experiment, including information on the selection and eligibility of participants is included.
  - [ ] A PDF copy of the instructions given to participants in both original language and an English translation is included.
- [ ] uses data generated via survey by the authors (in field or online)
  - [ ] The programs used to administer the survey (e.g. qualtrics survey file) are included.
  - [ ] A PDF copy of IRB approval is contained in the package.
  - [ ] A PDF of the original questionaire(s) and information on the selection and eligibility of participants is included.
- [ ] is a simulation study: the data are generated by an algorithm.
- [ ] is a numerical illustration: no data are used but code is used to produce illustrative output (tables, figures)


# Data description

For any data that cannot be provided as part of the replication package, please provide the following information as part of the README.



## Data Sources

| file/name            | public | private | DOI/URL | Access described| cited readme | cited paper |
| ----                 | ---    | ---     | ---     | ---             | ----         | ----        | 
| ASCII/BLS_CPI_6823.txt | yes    | no      | no     | yes              | yes          | no paper yet         |
| ASCII/Earnings_ASCII.txt.txt | yes    | no      | no     | yes              | yes          | no paper yet         |
|
 ASCII/Gid_pro_ASCII.txt | yes    | no      | no     | yes              | yes          | no paper yet         |
|
 ASCII/Income_ASCII.txt | yes    | no      | no     | yes              | yes          | no paper yet         |
 ASCII/Main_data_ASCII.txt | yes    | no      | no     | yes              | yes          | no paper yet         |

# Requirements 


- [X] README is in TXT, MD, or PDF format
- [X] README is accessible at the root of the package (not inside a folder)
- [X] Title conforms to guidance (starts with "Data and Code for: Title of Paper" or "Code for: Title of Paper", is properly capitalized)
- [X] Authors (with affiliations) are listed in the same order as on the paper



## Stated Requirements

- [ ] No requirements specified
- [X] Software Requirements specified as follows:
  - Vanilla Stata 19.0

- [ ] Computational Requirements specified as follows:

- [X] Time Requirements specified as follows:
  - Length of necessary computation: 2.25 mins

- [ ] Requirements are complete.

For missing requirements, see the list of required changes in @sec-findings

# Analyzing Data and Code Files


{{< include generated/report-pii.md >}}

{{< include generated/report-file-paths.md >}}

{{< include generated/report-duplicates.md >}}

{{< include generated/report-zero-files.md >}}

{{< include generated/report-large-files.md >}}



## Code description

### All produced data files
* BLS_CPI_2023.dta
* Earnings_clean.dta
* Earnings_raw.dta
* Gid_pro_clean.dta
* Gid_pro_raw.dta
* Income_clean.dta
* Income_raw.dta
* Minimal_PSID.dta
* parent_child_PSID.dta
* Reshaped.dta

It is not written in which analysis files they are produced.

### All analysis files
* 0_Main.do
* Data_cleaning.do
* Deflate.do
* Earnings_reader.do
* Gen_Income_Earnings.do
* Gid_pro_cleaner.do
* Gid_pro_reader.do
* Income_reader.do
* Main_data_reader.do
* Merging_GID_main.do
* Pill_IV.do
* RebaseCPI.do
* Regressions.do
* Role_related_variables.do

### Figure creation files
* Pill_IV.do

### Table creation files
* Regressions.do

{{< include generated/report-cloc.md >}}


[X] The replication package contains a "main" or "master" file(s) which calls all other auxiliary programs.

## Computing Environment of the Replicator

* 12th Gen Intel(R) Core(TM) i5-1235U (1.30 GHz), Installed RAM	16.0 GB, Intel(R) Iris(R) Xe Graphics (128 MB)
* Stata 18.0

# Replication

* Downloaded code and data from Zenodo repository.
* Ran code according to instructions in README file. Intuitively, I ran the main file `0_Main.do` which calls all other auxiliary programs. The code ran without errors and produced the expected output files.

# Findings {#sec-findings}

Everithing ran without errors and produced the expected output files. 
It is not clear which analysis files produce the data files.

| Data Preparation Program | Dataset created | Reproduced? |
|--------------------------|-----------------|-------------|
| ?                        | BLS_CPI_2023.dta | Yes        |
| ?                        | Earnings_clean.dta | Yes      |
| ?                        | Earnings_raw.dta | Yes        |
| ?                        | Gid_pro_clean.dta | Yes       |
| ?                        | Gid_pro_raw.dta | Yes        |
| ?                        | Income_clean.dta | Yes        |
| ?                        | Income_raw.dta | Yes          |
| ?                        | Minimal_PSID.dta | Yes        |
| ?                        | parent_child_PSID.dta | Yes   |
| ?                        | Reshaped.dta | Yes            |


| Figure/Table #          | Program         | Line Number       | Reproduced? |
|-------------------------|-----------------|-------------------|-------------|
| pill_by_state.png       | Pill_IV.do      | line: 360         | Yes         |
| Table1_covariates.tex   | Regressions.do  | lines: 1248-1308  | Yes         |
| Table2_covariates.tex   | Regressions.do  | lines: 1248-1308  | Yes         |
| Table3_covariates.tex   | Regressions.do  | lines: 1248-1308  | Yes         |
| Table_Educ_1.tex        | Regressions.do  | lines: 1339-1397  | Yes         |
| Table_Educ_2.tex        | Regressions.do  | lines: 1339-1397  | Yes         |

## Missing Requirements

## Data Preparation Code


## In-Text Numbers

- [ ] In-text numbers not verified.

- [X] There are no in-text numbers, or all in-text numbers stem from tables and figures.

- [ ] There are in-text numbers, but they are not identified in the code


## Other Issues

# Classification


- [X] full reproduction
- [ ] full reproduction with minor issues
- [ ] partial reproduction (see above)
- [ ] not able to reproduce most or all of the results (reasons see above)

## Reason for incomplete reproducibility


{{< include generated/report-pii.md >}}
